.. # Use http://b64.io/ to encode any image to base64. Then replace `/` with
   # `%2F` and `+` with `%2B` (or use http://meyerweb.com/eric/tools/dencoder/).
   # Beware that `?logo=data:image/png;base64,` must also be converted to
   # percent encoding so that the URL is properly parsed.

.. # Sourcecode link to GitHub
.. |SHIELD:svgreports-github| image:: https://img.shields.io/badge/pyTooling-sphinx--reports-63bf7f.svg?longCache=true&style=flat-square&longCache=true&logo=GitHub
   :alt: Sourcecode on GitHub
   :height: 22
   :target: https://GitHub.com/pyTooling/sphinx-reports
.. |SHIELD:pngreports-github| image:: https://raster.shields.io/badge/pyTooling-sphinx--reports-63bf7f.svg?longCache=true&style=flat-square&longCache=true&logo=GitHub
   :alt: Sourcecode on GitHub
   :height: 22
   :target: https://GitHub.com/pyTooling/sphinx-reports

.. # Sourcecode license
.. |SHIELD:svgreports-src-license| image:: https://img.shields.io/pypi/l/sphinx-reports?longCache=true&style=flat-square&logo=Apache&label=code
   :alt: Code license
   :height: 22
   :target: Code-License.html
.. |SHIELD:pngreports-src-license| image:: https://img.shields.io/pypi/l/sphinx-reports?longCache=true&style=flat-square&logo=Apache&label=code
   :alt: Code license
   :height: 22
   :target: https://GitHub.com/pyTooling/sphinx-reports/blob/main/LICENSE.md

.. # GitHub tag
.. |SHIELD:svgreports-tag| image:: https://img.shields.io/github/v/tag/pyTooling/sphinx-reports?longCache=true&style=flat-square&logo=GitHub&include_prereleases
   :alt: GitHub tag (latest SemVer incl. pre-release
   :height: 22
   :target: https://GitHub.com/pyTooling/sphinx-reports/tags
.. |SHIELD:pngreports-tag| image:: https://raster.shields.io/github/v/tag/pyTooling/sphinx-reports?longCache=true&style=flat-square&logo=GitHub&include_prereleases
   :alt: GitHub tag (latest SemVer incl. pre-release
   :height: 22
   :target: https://GitHub.com/pyTooling/sphinx-reports/tags

.. # GitHub release date
.. |SHIELD:svgreports-date| image:: https://img.shields.io/github/release-date/pyTooling/sphinx-reports?longCache=true&style=flat-square&logo=GitHub
   :alt: GitHub release date
   :height: 22
   :target: https://GitHub.com/pyTooling/sphinx-reports/releases
.. |SHIELD:pngreports-date| image:: https://raster.shields.io/github/release-date/pyTooling/sphinx-reports?longCache=true&style=flat-square&logo=GitHub
   :alt: GitHub release date
   :height: 22
   :target: https://GitHub.com/pyTooling/sphinx-reports/releases

.. # GitHub/Libraries dependent projects
.. |SHIELD:svgreports-lib-dep| image:: https://img.shields.io/librariesio/dependent-repos/pypi/sphinx-reports?longCache=true&style=flat-square&logo=Libraries.io&logoColor=fff
   :alt: Dependent repos (via libraries.io)
   :height: 22
   :target: https://GitHub.com/pyTooling/sphinx-reports/network/dependents
.. |SHIELD:pngreports-lib-dep| image:: https://raster.shields.io/librariesio/dependent-repos/pypi/sphinx-reports?longCache=true&style=flat-square&logo=Libraries.io&logoColor=fff
   :alt: Dependent repos (via libraries.io)
   :height: 22
   :target: https://GitHub.com/pyTooling/sphinx-reports/network/dependents

.. # GHA test and coverage
.. |SHIELD:svgreports-gha-test| image:: https://img.shields.io/github/actions/workflow/status/pyTooling/sphinx-reports/Pipeline.yml?branch=main&longCache=true&style=flat-square&label=Build%20and%20Test&logo=GitHub%20Actions&logoColor=FFFFFF
   :alt: GitHub Workflow - Build and Test Status
   :height: 22
   :target: https://GitHub.com/pyTooling/sphinx-reports/actions/workflows/Pipeline.yml
.. |SHIELD:pngreports-gha-test| image:: https://raster.shields.io/github/actions/workflow/status/pyTooling/sphinx-reports/Pipeline.yml?branch=main&longCache=true&style=flat-square&label=Build%20and%20Test&logo=GitHub%20Actions&logoColor=FFFFFF
   :alt: GitHub Workflow - Build and Test Status
   :height: 22
   :target: https://GitHub.com/pyTooling/sphinx-reports/actions/workflows/Pipeline.yml

.. # Codacy - quality
.. |SHIELD:svgreports-codacy-quality| image:: https://img.shields.io/codacy/grade/8dc5205ba8b24e008f2287759096e181?longCache=true&style=flat-square&logo=codacy
   :alt: Codacy - Quality
   :height: 22
   :target: https://www.codacy.com/gh/pyTooling/sphinx-reports
.. |SHIELD:pngreports-codacy-quality| image:: https://raster.shields.io/codacy/grade/8dc5205ba8b24e008f2287759096e181?longCache=true&style=flat-square&logo=codacy
   :alt: Codacy - Quality
   :height: 22
   :target: https://www.codacy.com/gh/pyTooling/sphinx-reports

.. # Codacy - coverage
.. |SHIELD:svgreports-codacy-coverage| image:: https://img.shields.io/codacy/coverage/8dc5205ba8b24e008f2287759096e181?longCache=true&style=flat-square&logo=codacy
   :alt: Codacy - Line Coverage
   :height: 22
   :target: https://www.codacy.com/gh/pyTooling/sphinx-reports
.. |SHIELD:pngreports-codacy-coverage| image:: https://raster.shields.io/codacy/coverage/8dc5205ba8b24e008f2287759096e181?longCache=true&style=flat-square&logo=codacy
   :alt: Codacy - Line Coverage
   :height: 22
   :target: https://www.codacy.com/gh/pyTooling/sphinx-reports

.. # Codecov - coverage
.. |SHIELD:svgreports-codecov-coverage| image:: https://img.shields.io/codecov/c/github/pyTooling/sphinx-reports?longCache=true&style=flat-square&logo=Codecov
   :alt: Codecov - Branch Coverage
   :height: 22
   :target: https://codecov.io/gh/pyTooling/sphinx-reports
.. |SHIELD:pngreports-codecov-coverage| image:: https://raster.shields.io/codecov/c/github/pyTooling/sphinx-reports?longCache=true&style=flat-square&logo=Codecov
   :alt: Codecov - Branch Coverage
   :height: 22
   :target: https://codecov.io/gh/pyTooling/sphinx-reports

.. # Libraries - source rank
.. |SHIELD:svgreports-lib-rank| image:: https://img.shields.io/librariesio/sourcerank/pypi/sphinx-reports?longCache=true&style=flat-square&logo=Libraries.io&logoColor=fff
   :alt: Libraries.io SourceRank
   :height: 22
   :target: https://libraries.io/github/pyTooling/sphinx-reports/sourcerank
.. |SHIELD:pngreports-lib-rank| image:: https://raster.shields.io/librariesio/sourcerank/pypi/sphinx-reports?longCache=true&style=flat-square&logo=Libraries.io&logoColor=fff
   :alt: Libraries.io SourceRank
   :height: 22
   :target: https://libraries.io/github/pyTooling/sphinx-reports/sourcerank

.. # PyPI tag
.. |SHIELD:svgreports-pypi-tag| image:: https://img.shields.io/pypi/v/sphinx-reports?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Tag
   :height: 22
   :target: https://pypi.org/project/sphinx-reports/
.. |SHIELD:pngreports-pypi-tag| image:: https://raster.shields.io/pypi/v/sphinx-reports?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Tag
   :height: 22
   :target: https://pypi.org/project/sphinx-reports/

.. # PyPI project status
.. |SHIELD:svgreports-pypi-status| image:: https://img.shields.io/pypi/status/sphinx-reports?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Status
   :height: 22
.. |SHIELD:pngreports-pypi-status| image:: https://raster.shields.io/pypi/status/sphinx-reports?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Status
   :height: 22

.. # PyPI Python versions
.. |SHIELD:svgreports-pypi-python| image:: https://img.shields.io/pypi/pyversions/sphinx-reports?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Python Version
   :height: 22
.. |SHIELD:pngreports-pypi-python| image:: https://raster.shields.io/pypi/pyversions/sphinx-reports?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Python Version
   :height: 22

.. # Libraries - status
.. |SHIELD:svgreports-lib-status| image:: https://img.shields.io/librariesio/release/pypi/sphinx-reports?longCache=true&style=flat-square&logo=Libraries.io&logoColor=fff
   :alt: Libraries.io status for latest release
   :height: 22
   :target: https://libraries.io/github/pyTooling/sphinx-reports
.. |SHIELD:pngreports-lib-status| image:: https://raster.shields.io/librariesio/release/pypi/sphinx-reports?longCache=true&style=flat-square&logo=Libraries.io&logoColor=fff
   :alt: Libraries.io status for latest release
   :height: 22
   :target: https://libraries.io/github/pyTooling/sphinx-reports

.. # Documentation license
.. |SHIELD:svgreports-doc-license| image:: https://img.shields.io/badge/doc-CC--BY%204.0-green?longCache=true&style=flat-square&logo=CreativeCommons&logoColor=fff
   :alt: Documentation License
   :height: 22
   :target: License.html
.. |SHIELD:pngreports-doc-license| image:: https://raster.shields.io/badge/doc-CC--BY%204.0-green?longCache=true&style=flat-square&logo=CreativeCommons&logoColor=fff
   :alt: Documentation License
   :height: 22
   :target: https://GitHub.com/pyTooling/sphinx-reports/blob/main/doc/License.rst

.. # GHPages - read now
.. |SHIELD:svgreports-ghp-doc| image:: https://img.shields.io/website?longCache=true&style=flat-square&label=pyTooling.github.io%2Fsphinx-reports&logo=GitHub&logoColor=fff&up_color=blueviolet&up_message=Read%20now%20%E2%9E%9A&url=https%3A%2F%2FpyTooling.github.io%2Fsphinx-reports%2Findex.html
   :alt: Documentation - Read Now!
   :height: 22
   :target: https://pyTooling.github.io/sphinx-reports/
.. |SHIELD:pngreports-ghp-doc| image:: https://raster.shields.io/website?longCache=true&style=flat-square&label=pyTooling.github.io%2Fsphinx-reports&logo=GitHub&logoColor=fff&up_color=blueviolet&up_message=Read%20now%20%E2%9E%9A&url=https%3A%2F%2FpyTooling.github.io%2Fsphinx-reports%2Findex.html
   :alt: Documentation - Read Now!
   :height: 22
   :target: https://pyTooling.github.io/sphinx-reports/

.. # Gitter
.. |SHIELD:svgreports-gitter| image:: https://img.shields.io/badge/chat-on%20gitter-4db797.svg?longCache=true&style=flat-square&logo=gitter&logoColor=e8ecef
   :alt: Documentation License
   :height: 22
   :target: https://gitter.im/hdl/community
.. |SHIELD:pngreports-gitter| image:: https://raster.shields.io/badge/chat-on%20gitter-4db797.svg?longCache=true&style=flat-square&logo=gitter&logoColor=e8ecef
   :alt: Documentation License
   :height: 22
   :target: https://gitter.im/hdl/community
