.. # Use http://b64.io/ to encode any image to base64. Then replace `/` with
   # `%2F` and `+` with `%2B` (or use http://meyerweb.com/eric/tools/dencoder/).
   # Beware that `?logo=data:image/png;base64,` must also be converted to
   # percent encoding so that the URL is properly parsed.

.. # Sourcecode link to GitHub
.. |SHIELD:svg:SphinxReports-github| image:: https://img.shields.io/badge/pyTooling-sphinx--reports-323131?longCache=true&style=flat-square&longCache=true&logo=GitHub
   :alt: Sourcecode on GitHub
   :height: 22
   :target: https://GitHub.com/pyTooling/sphinx-reports
.. |SHIELD:png:SphinxReports-github| image:: https://raster.shields.io/badge/pyTooling-sphinx--reports-323131?longCache=true&style=flat-square&longCache=true&logo=GitHub
   :alt: Sourcecode on GitHub
   :height: 22
   :target: https://GitHub.com/pyTooling/sphinx-reports

.. # Sourcecode license
.. |SHIELD:svg:SphinxReports-src-license| image:: https://img.shields.io/pypi/l/sphinx-reports?longCache=true&style=flat-square&logo=Apache&label=code
   :alt: Code license
   :height: 22
   :target: Code-License.html
.. |SHIELD:png:SphinxReports-src-license| image:: https://img.shields.io/pypi/l/sphinx-reports?longCache=true&style=flat-square&logo=Apache&label=code
   :alt: Code license
   :height: 22
   :target: https://GitHub.com/pyTooling/sphinx-reports/blob/main/LICENSE.md

.. # GitHub tag
.. |SHIELD:svg:SphinxReports-tag| image:: https://img.shields.io/github/v/tag/pyTooling/sphinx-reports?longCache=true&style=flat-square&logo=GitHub&include_prereleases
   :alt: GitHub tag (latest SemVer incl. pre-release
   :height: 22
   :target: https://GitHub.com/pyTooling/sphinx-reports/tags
.. |SHIELD:png:SphinxReports-tag| image:: https://raster.shields.io/github/v/tag/pyTooling/sphinx-reports?longCache=true&style=flat-square&logo=GitHub&include_prereleases
   :alt: GitHub tag (latest SemVer incl. pre-release
   :height: 22
   :target: https://GitHub.com/pyTooling/sphinx-reports/tags

.. # GitHub release date
.. |SHIELD:svg:SphinxReports-date| image:: https://img.shields.io/github/release-date/pyTooling/sphinx-reports?longCache=true&style=flat-square&logo=GitHub
   :alt: GitHub release date
   :height: 22
   :target: https://GitHub.com/pyTooling/sphinx-reports/releases
.. |SHIELD:png:SphinxReports-date| image:: https://raster.shields.io/github/release-date/pyTooling/sphinx-reports?longCache=true&style=flat-square&logo=GitHub
   :alt: GitHub release date
   :height: 22
   :target: https://GitHub.com/pyTooling/sphinx-reports/releases

.. # GitHub/Libraries dependent projects
.. |SHIELD:svg:SphinxReports-lib-dep| image:: https://img.shields.io/librariesio/dependent-repos/pypi/sphinx-reports?longCache=true&style=flat-square&logo=Libraries.io&logoColor=fff
   :alt: Dependent repos (via libraries.io)
   :height: 22
   :target: https://GitHub.com/pyTooling/sphinx-reports/network/dependents
.. |SHIELD:png:SphinxReports-lib-dep| image:: https://raster.shields.io/librariesio/dependent-repos/pypi/sphinx-reports?longCache=true&style=flat-square&logo=Libraries.io&logoColor=fff
   :alt: Dependent repos (via libraries.io)
   :height: 22
   :target: https://GitHub.com/pyTooling/sphinx-reports/network/dependents

.. # GHA test and coverage
.. |SHIELD:svg:SphinxReports-gha-test| image:: https://img.shields.io/github/actions/workflow/status/pyTooling/sphinx-reports/Pipeline.yml?branch=main&longCache=true&style=flat-square&label=Build%20and%20Test&logo=GitHub%20Actions&logoColor=FFFFFF
   :alt: GitHub Workflow - Build and Test Status
   :height: 22
   :target: https://GitHub.com/pyTooling/sphinx-reports/actions/workflows/Pipeline.yml
.. |SHIELD:png:SphinxReports-gha-test| image:: https://raster.shields.io/github/actions/workflow/status/pyTooling/sphinx-reports/Pipeline.yml?branch=main&longCache=true&style=flat-square&label=Build%20and%20Test&logo=GitHub%20Actions&logoColor=FFFFFF
   :alt: GitHub Workflow - Build and Test Status
   :height: 22
   :target: https://GitHub.com/pyTooling/sphinx-reports/actions/workflows/Pipeline.yml

.. # Codacy - quality
.. |SHIELD:svg:SphinxReports-codacy-quality| image:: https://img.shields.io/codacy/grade/9a89bbc1d2c04a699ea14abea75588c7?longCache=true&style=flat-square&logo=codacy
   :alt: Codacy - Quality
   :height: 22
   :target: https://www.codacy.com/gh/pyTooling/sphinx-reports
.. |SHIELD:png:SphinxReports-codacy-quality| image:: https://raster.shields.io/codacy/grade/9a89bbc1d2c04a699ea14abea75588c7?longCache=true&style=flat-square&logo=codacy
   :alt: Codacy - Quality
   :height: 22
   :target: https://www.codacy.com/gh/pyTooling/sphinx-reports

.. # Codacy - coverage
.. |SHIELD:svg:SphinxReports-codacy-coverage| image:: https://img.shields.io/codacy/coverage/9a89bbc1d2c04a699ea14abea75588c7?longCache=true&style=flat-square&logo=codacy
   :alt: Codacy - Line Coverage
   :height: 22
   :target: https://www.codacy.com/gh/pyTooling/sphinx-reports
.. |SHIELD:png:SphinxReports-codacy-coverage| image:: https://raster.shields.io/codacy/coverage/9a89bbc1d2c04a699ea14abea75588c7?longCache=true&style=flat-square&logo=codacy
   :alt: Codacy - Line Coverage
   :height: 22
   :target: https://www.codacy.com/gh/pyTooling/sphinx-reports

.. # Codecov - coverage
.. |SHIELD:svg:SphinxReports-codecov-coverage| image:: https://img.shields.io/codecov/c/github/pyTooling/sphinx-reports?longCache=true&style=flat-square&logo=Codecov
   :alt: Codecov - Branch Coverage
   :height: 22
   :target: https://codecov.io/gh/pyTooling/sphinx-reports
.. |SHIELD:png:SphinxReports-codecov-coverage| image:: https://raster.shields.io/codecov/c/github/pyTooling/sphinx-reports?longCache=true&style=flat-square&logo=Codecov
   :alt: Codecov - Branch Coverage
   :height: 22
   :target: https://codecov.io/gh/pyTooling/sphinx-reports

.. # Libraries - source rank
.. |SHIELD:svg:SphinxReports-lib-rank| image:: https://img.shields.io/librariesio/sourcerank/pypi/sphinx-reports?longCache=true&style=flat-square&logo=Libraries.io&logoColor=fff
   :alt: Libraries.io SourceRank
   :height: 22
   :target: https://libraries.io/github/pyTooling/sphinx-reports/sourcerank
.. |SHIELD:png:SphinxReports-lib-rank| image:: https://raster.shields.io/librariesio/sourcerank/pypi/sphinx-reports?longCache=true&style=flat-square&logo=Libraries.io&logoColor=fff
   :alt: Libraries.io SourceRank
   :height: 22
   :target: https://libraries.io/github/pyTooling/sphinx-reports/sourcerank

.. # PyPI tag
.. |SHIELD:svg:SphinxReports-pypi-tag| image:: https://img.shields.io/pypi/v/sphinx-reports?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Tag
   :height: 22
   :target: https://pypi.org/project/sphinx-reports/
.. |SHIELD:png:SphinxReports-pypi-tag| image:: https://raster.shields.io/pypi/v/sphinx-reports?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Tag
   :height: 22
   :target: https://pypi.org/project/sphinx-reports/

.. # PyPI project status
.. |SHIELD:svg:SphinxReports-pypi-status| image:: https://img.shields.io/pypi/status/sphinx-reports?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Status
   :height: 22
.. |SHIELD:png:SphinxReports-pypi-status| image:: https://raster.shields.io/pypi/status/sphinx-reports?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Status
   :height: 22

.. # PyPI Python versions
.. |SHIELD:svg:SphinxReports-pypi-python| image:: https://img.shields.io/pypi/pyversions/sphinx-reports?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Python Version
   :height: 22
.. |SHIELD:png:SphinxReports-pypi-python| image:: https://raster.shields.io/pypi/pyversions/sphinx-reports?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Python Version
   :height: 22

.. # Libraries - status
.. |SHIELD:svg:SphinxReports-lib-status| image:: https://img.shields.io/librariesio/release/pypi/sphinx-reports?longCache=true&style=flat-square&logo=Libraries.io&logoColor=fff
   :alt: Libraries.io status for latest release
   :height: 22
   :target: https://libraries.io/github/pyTooling/sphinx-reports
.. |SHIELD:png:SphinxReports-lib-status| image:: https://raster.shields.io/librariesio/release/pypi/sphinx-reports?longCache=true&style=flat-square&logo=Libraries.io&logoColor=fff
   :alt: Libraries.io status for latest release
   :height: 22
   :target: https://libraries.io/github/pyTooling/sphinx-reports

.. # Documentation license
.. |SHIELD:svg:SphinxReports-doc-license| image:: https://img.shields.io/badge/doc-CC--BY%204.0-green?longCache=true&style=flat-square&logo=CreativeCommons&logoColor=fff
   :alt: Documentation License
   :height: 22
   :target: License.html
.. |SHIELD:png:SphinxReports-doc-license| image:: https://raster.shields.io/badge/doc-CC--BY%204.0-green?longCache=true&style=flat-square&logo=CreativeCommons&logoColor=fff
   :alt: Documentation License
   :height: 22
   :target: https://GitHub.com/pyTooling/sphinx-reports/blob/main/doc/License.rst

.. # GHPages - read now
.. |SHIELD:svg:SphinxReports-ghp-doc| image:: https://img.shields.io/website?longCache=true&style=flat-square&label=pyTooling.github.io%2Fsphinx%2Dreports&logo=GitHub&logoColor=fff&up_color=blueviolet&up_message=Read%20now%20%E2%9E%9A&url=https%3A%2F%2FpyTooling.github.io%2Fsphinx%2Dreports%2Findex.html
   :alt: Documentation - Read Now!
   :height: 22
   :target: https://pyTooling.github.io/sphinx-reports/
.. |SHIELD:png:SphinxReports-ghp-doc| image:: https://raster.shields.io/website?longCache=true&style=flat-square&label=pyTooling.github.io%2Fsphinx%2Dreports&logo=GitHub&logoColor=fff&up_color=blueviolet&up_message=Read%20now%20%E2%9E%9A&url=https%3A%2F%2FpyTooling.github.io%2Fsphinx%2Dreports%2Findex.html
   :alt: Documentation - Read Now!
   :height: 22
   :target: https://pyTooling.github.io/sphinx-reports/

.. # Gitter
.. |SHIELD:svg:SphinxReports-gitter| image:: https://img.shields.io/badge/chat-on%20gitter-4db797?longCache=true&style=flat-square&logo=gitter&logoColor=e8ecef
   :alt: Documentation License
   :height: 22
   :target: https://gitter.im/hdl/community
.. |SHIELD:png:SphinxReports-gitter| image:: https://raster.shields.io/badge/chat-on%20gitter-4db797?longCache=true&style=flat-square&logo=gitter&logoColor=e8ecef
   :alt: Documentation License
   :height: 22
   :target: https://gitter.im/hdl/community
