name: Pipeline

on:
  push:
  workflow_dispatch:
  schedule:
# Every Friday at 22:00 - rerun pipeline to check for dependency-based issues
    - cron: '0 22 * * 5'

jobs:
  Pipeline:
    uses: pyTooling/Actions/.github/workflows/CompletePipeline.yml@dev
    permissions:
      contents: write  # required for create tag
      actions:  write  # required for trigger workflow
    with:
      package_name: sphinx_reports
      unittest_python_version_list: '3.11 3.12 3.13'
      codecov: true
      codacy:  true
      dorny:   true
    secrets:
      PYPI_TOKEN:    ${{ secrets.PYPI_TOKEN }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      CODACY_TOKEN:  ${{ secrets.CODACY_TOKEN }}
